#!/bin/bash

# Array of collections to restore
collections=(
"collection1",
"collection2")

# MongoDB Atlas connection parameters
ATLAS_URI="mongodb+srv://username:password0@cluster.mongodb.net/"
DB_NAME="name-of-database"  # Replace with your database name

# Directory containing the dump files
DATE=$(date +%Y%m%d)
DUMP_DIR="./name_of_folder-backup-dump_$DATE"

# Loop through collections and drop each one
for collection in "${collections[@]}"
do
    echo "Dropping collection: $collection"
    mongosh "$ATLAS_URI" --eval "db.getSiblingDB('$DB_NAME').$collection.drop()"
done

# Loop through collections and perform mongorestore on each
for collection in "${collections[@]}"
do
    echo "Restoring collection: $collection"
    mongorestore --uri "$ATLAS_URI" --db $DB_NAME --collection $collection --drop $DUMP_DIR/$DB_NAME/$collection.bson
done

echo "MongoDB restore completed."
